### ISSUE TITLE
Not able to connect PHP application to db2 on remote server

### ISSUE THREAD

**Issue by bohsen** [nagstaku/php_db2#1]
Hi.

Thank you for this project - it's been an excellent ressource the last couple of days.
Been struggling connecting a PHP site to a remote DB2 database for the last three days in a docker-compose project I'm working on. Looking for solutions I stumbled across this yesterday and gave it a go, but ran into the same issue that I've been seeing on my own project - `Connection failed`:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/355452/190845370-b5dba927-ba6e-4da4-ac51-d5cdfe110dc7.png">

Here's my docker-compose setup:
```
# /wordpress-docker/docker-compose.yml
---
version: '3.8'
services:
  web:
    container_name: nginx
    depends_on:
      - db2
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    links:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  db2:
    container_name: db2
    image: ibmcom/db2:latest
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - DB_NAME=testdb
      - DB_USER=db2inst1
      - DB_PASSWORD=ChangeMe!
      - LICENSE=accept
      ## Creates the database DB_NAME, if its not exists
      - STARTUP_MODE=createIfNotExists
      - DB_CREATE_SCRIPT=create_wdemo.sql
      ## loads an old backup of DB_NAME, 
      ## if the dabase DB_NAME does not exist
      # - STARTUP_MODE=restoreIfNotExists
      # - DB_BACKUP=wdemo.tar.gz
    volumes:
      - './data/db2:/database'
```
And the PHP.dockerfile:
```
FROM php:fpm

RUN apt-get update -qq > /dev/null && \
    apt-get install unzip
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Documentation
# https://stackoverflow.com/questions/37066985/php-connection-to-db2
# https://github.com/nagstaku/php_db2
# https://github.com/php/pecl-database-ibm_db2
# https://github.com/php/pecl-database-pdo_ibm

# Install DB2 php-extensions

RUN mkdir -p /opt/ibm/ && curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz | tar -xz -C /opt/ibm/
# if you prefer to keep the file locally, download it and use:
COPY v11.5.4_linuxx64_dsdriver.tar.gz /opt/ibm/
RUN cd /opt/ibm/ && \
    gunzip v11.5.4_linuxx64_dsdriver.tar.gz && \
    tar -xvf v11.5.4_linuxx64_dsdriver.tar

## set env vars needed for PECL install
ENV IBM_DB_HOME=/opt/ibm/clidriver
ENV LD_LIBRARY_PATH=/opt/ibm/clidriver/lib

## install ibm_db2 drivers
RUN pecl install ibm_db2 pdo_ibm
RUN echo "extension=ibm_db2.so" > /usr/local/etc/php/conf.d/ibm_db2.ini
RUN echo "extension=pdo.so" > /usr/local/etc/php/php.ini
RUN echo "extension=pdo_ibm.so" > /usr/local/etc/php/php.ini
```
Output from my project (with extra debug info):
<img width="945" alt="image" src="https://user-images.githubusercontent.com/355452/190845712-53a76fa0-4df2-4b6f-b01b-cba788938596.png">
Is there something I'm missing regarding the setup, that isn't documented anywhere?

Best regards,
Thomas

**Comment by Matwy** [comment]
Hi, I'm also trying to connect to a remote DB2 database. Have you found a solution?

**Comment by bohsen** [comment]
@Matwy I have actually. See code below - please notice that it takes around 3 minutes to start the DB2-instance.

docker-compose.yml:
```
# /wordpress-docker/docker-compose.yml
---
version: '3.8'
services:
  web:
    container_name: nginx
    depends_on:
      - db2
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    links:
      - php
      - db2
  php:
    container_name: php
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    links:
      - db2
  db2:
    container_name: db2
    image: ibmcom/db2:latest
    hostname: db2.rn.dk
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - DBNAME=testdb
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=ChangeMe1
      - LICENSE=accept
      # - SAMPLEDB=true
      ## Creates the database DB_NAME, if its not exists
      # - STARTUP_MODE=createIfNotExists
      # - DB_CREATE_SCRIPT=create_wdemo.sql
      ## loads an old backup of DB_NAME, 
      ## if the dabase DB_NAME does not exist
      # - STARTUP_MODE=restoreIfNotExists
      # - DB_BACKUP=wdemo.tar.gz
    volumes:
      - './data/db2:/database'
```

PHP Dockerfile:
```
FROM php:fpm

RUN apt-get update -qq > /dev/null && \
    apt-get install unzip
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Documentation
# https://www.ibm.com/docs/en/db2/11.5?topic=dsd-installing-data-server-driver-odbc-cli-software-linux-unix-operating-systems
# https://www.ibm.com/docs/en/db2/11.5?topic=environment-configuring
# https://stackoverflow.com/questions/37066985/php-connection-to-db2
# https://github.com/nagstaku/php_db2
# https://github.com/php/pecl-database-ibm_db2
# https://github.com/php/pecl-database-pdo_ibm

# Install DB2 php-extensions

RUN mkdir -p /opt/ibm/ && curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz | tar -xz -C /opt/ibm/

## set env vars needed for PECL install
ENV IBM_DB_HOME=/opt/ibm/clidriver
ENV LD_LIBRARY_PATH=/opt/ibm/clidriver/lib

## install ibm_db2 drivers
RUN pecl install ibm_db2 --with-IBM_DB2=/opt/clidriver
RUN echo "extension=ibm_db2.so" >> /usr/local/etc/php/php.ini
```

nginx.conf:
```
server {
   listen 80 default_server;
   root /app/public;
   index index.php index.html index.htm;
   location ~ \.php$ {
       fastcgi_pass php:9000;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       include fastcgi_params;
   }
}
```
